### ISSUE TITLE
implicit order not correct

### ISSUE THREAD

**Issue by tiboun** [starlake-ai/jsqltranspiler#10]
Using BigQuery Translation, the following unit test doesn't have bigquery expecting result:

```sql
SELECT
  x,
  AVG(x) OVER (ORDER BY x ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS avg
FROM UNNEST([0, 2, NULL, 4, 4, 5]) AS x;
```

Expecting result is

> /*------+------*
>  | x    | avg  |
>  +------+------+
>  | NULL | NULL |
>  | 0    | 0    |
>  | 2    | 1    |
>  | 4    | 3    |
>  | 4    | 4    |
>  | 5    | 4.5  |
>  *------+------*/

Current expectation is 

> "x","avg"
> "0","0.0"
> "2","1.0"
> "4","3.0"
> "4","4.0"
> "5","4.5"
> "","5.0"

with the following transpilation:

```sql
SELECT
  x,
  AVG(x) OVER (ORDER BY x ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS avg
FROM (select UNNEST([0, 2, NULL, 4, 4, 5]) AS x) as x;
```

Bigquery ORDER BY's rule is the [following](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#order_by_clause).

DuckDB's one is the [following](https://duckdb.org/docs/sql/query_syntax/orderby.html).

From these documentation, expecting transpilation is:

```sql
SELECT
  x,
  AVG(x) OVER (ORDER BY x NULLS FIRST ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS avg
FROM (select UNNEST([0, 2, NULL, 4, 4, 5]) AS x) as x;
```
because Bigquery order by NULLS FIRST by default with value order ASC. In DUCKDB it's NULLS LAST by default with value order ASC.

**Comment by manticore-projects** [comment]
Greetings!

Thank you for reporting, however in my opinion this is not a challenge of JSQLTranspiler itself. Rather you will need to set a few options in DuckDB before executing your transpiled statements:

```sql

SET default_null_order = 'NULLS FIRST';
SET default_order = 'ASC';
SET old_implicit_casting=True;
```

Alternatively, you can provide those as Connection Properties:
```java
    // Currently, Duck DB Home resolution in Java seems broken
    File fileDuckDB =
        new File(EXTRACTION_PATH, JSQLTranspilerTest.class.getSimpleName() + ".duckdb");
    Properties info = new Properties();
    info.put("old_implicit_casting", "true");
    info.put("default_null_order", "NULLS FIRST");
    info.put("default_order", "ASC");
    connDuck = DriverManager.getConnection("jdbc:duckdb:" + fileDuckDB.getAbsolutePath(), info);
```

**Comment by manticore-projects** [comment]
As a remedy for the JSQLParser Tests, I have introduced:
```java
        if (t.inputDialect==JSQLTranspiler.Dialect.GOOGLE_BIG_QUERY) {
          st.executeUpdate("set default_null_order='NULLS FIRST'");
          st.executeUpdate("set default_order='ASC'");
        }
'''

Do let me kn ow if similar settings are needed for any other Output Dialect.
