### ISSUE TITLE
feature: Pass CURRENT_TIMESTAMP & CURRENT_DATE as  parameters

### ISSUE THREAD

**Issue by hayssams** [starlake-ai/jsqltranspiler#17]
Would it be possible to call the transpile function with an map of options parameters containing the CURRENT_TIMESTAMP & CURRENT_DATE values ?

**Comment by manticore-projects** [comment]
Greetings!

You can rewrite any time key like `CURRENT_TIMESTAMP` by setting a key/value pair in `System.properties` as shown here: https://github.com/starlake-ai/jsqltranspiler?tab=readme-ov-file#timekey-substitution

Are you referring to this or do you need this as an additional feature please?

**Comment by hayssams** [comment]
Actually, we need to set it on a per call level not on a per JVM.
That's why I was requesting such a feature.
Thanks

**Comment by manticore-projects** [comment]
Ok, got it. I would work on this and provide by tomorrow.
