### ISSUE TITLE
avoid usage of javax.swing classes

### ISSUE THREAD

**Issue by stbischof** [starlake-ai/jsqltranspiler#20]
Some Server JRE do not package the javax.swing modules.

Also if you use jdeps and jlink  to shrink your jdk you cant get rif of javax.swing.

https://github.com/starlake-ai/jsqltranspiler/blob/62e13865bcab312266371e1d3668deacf267006f/src/main/java/ai/starlake/transpiler/schema/JdbcColumn.java#L23C25-L23C33

please create and use you own Interface to walk the tree

**Comment by stbischof** [comment]
Are you open for a pr on that?

**Comment by manticore-projects** [comment]
certainly, we do look forward.
