### ISSUE TITLE
failing snapshot action

### ISSUE THREAD

**Issue by stbischof** [starlake-ai/jsqltranspiler#28]
the snapshot build action is broken because of some test.

could you please fix the test/impl

**Comment by manticore-projects** [comment]
Yes, we are aware of this and we are working on getting Snapshot deployment of JSQLParser working again. Give me a few days on this, we are depending on @Wumpz here.

**Comment by manticore-projects** [comment]
This is becoming a showstopper and unfortunately only @Wumpz can fix the JSQLParser snapshot publishing.
So we have two options:
a) chose our own Maven coordinates for JSQLParser or
b) include a precompiled JSQLParser (again, at least until this is fixed)

**Comment by manticore-projects** [comment]
There are still 2 tests failing on GitHub only -- and I don't have any idea why exactly.

**Comment by hayssams** [comment]
It has probably something to do with the precision, scale of the tests. Most of them fail one my Mac for this simple reason.

**Comment by manticore-projects** [comment]
I have reworked the Tests and the use of CSV to ensure similar precision on different platforms.
However, there are still 4 tests failing on GitHub and a few more on @hayssams Apple system. I will need to setup a clean virtual machine to understand what's going on.

**Comment by manticore-projects** [comment]
I have finally found and understood the 4 failing test cases. It was about "NULLS FIRST DEFAULT" order and I set this as a configuration for the test case now -- and the tests succeeded on GitHub.
Also I have removed the dependency to Linux SED, so everything should work now.
