### ISSUE TITLE
BIGQUERY SAFE_CAST not transpiled into duckdb TRY_CAST

### ISSUE THREAD

**Issue by fupelaqu** [starlake-ai/jsqltranspiler#34]
The BQ function safe_cast should be transpiled into try_cast

eg : 
`select safe_cast('_' as FLOAT64)` should be transpiled as `select try_cast('_' as FLOAT)`

**Comment by manticore-projects** [comment]
Thank you for reporting!
I am looking forward receiving more issues from you, please just keep them coming.

**Comment by fupelaqu** [comment]
you are welcome :)
