### ISSUE TITLE
JSQLTranspiler fails to resolve to the source table

### ISSUE THREAD

**Issue by hayssams** [starlake-ai/jsqltranspiler#45]
Added the two tests: testSelectAlias & testSelectCTEAlias to the branch below:
- https://github.com/starlake-ai/jsqltranspiler/tree/fix/resolve-alias

**Comment by manticore-projects** [comment]
fixed via https://github.com/starlake-ai/jsqltranspiler/commit/69106e4adeb1acbd36909a82772aee36220c1c75
