### ISSUE TITLE
Quote not translated correctly

### ISSUE THREAD

**Issue by tiboun** [starlake-ai/jsqltranspiler#9]
Given the following Bigquery query

```sql
SELECT ANY_VALUE(fruit) as any_value
FROM UNNEST(["apple", "banana", "pear"]) as fruit;
```

It gets translated into:

```sql
SELECT Any_Value( fruit ) AS any_value
FROM (  SELECT Unnest(  [ "apple", "banana", "pear"] ) AS fruit  ) AS fruit
;
```

Running this query throws

> Binder Error: Referenced column "apple" not found in FROM clause!
> LINE 2: FROM (  SELECT Unnest(  [ ... 

I guess Duckdb string quoting support only `'` and needs to be translated.

Expected output result for this query is random so running a determinist version of this query in order to test quote translation may be:

```sql
SELECT max(fruit) as any_value
FROM UNNEST(["apple", "banana", "pear"]) as fruit;
```

with expecting result

```
"any_value"
"pear"
```

**Comment by manticore-projects** [comment]
This has been improved and Double Quoted String Literals are now translated into Single Quoted String Literals -- on BigQuery only and via a Regular Expression, before parsing and transpiling.
